#include <common.h>

#include "..\..\..\include\helper_menu_box.h"

////////////////// Main Menu Rows //////////////////

#define UDCTRM_OM_ROW_ADVENTURE 0
#define UDCTRM_OM_ROW_TIME_TRIAL 1
#define UDCTRM_OM_ROW_ARCADE 2
#define UDCTRM_OM_ROW_VERSUS 3
#define UDCTRM_OM_ROW_BATTLE 4
#define UDCTRM_OM_ROW_HIGH_SCORE 5
#define UDCTRM_OM_ROW_SCRAPBOOK 6
#define UDCTRM_OM_ROW_OPTIONS 7
#define UDCTRM_OM_NUM_ROWS 8

void UDCTRM_OM_FuncPtr(struct MenuBox* mb);

struct MenuBox UDCTRM_OM_MenuBox =
{
    .stringIndexTitle = -1,

    .posX_curr = 0,
    .posY_curr = 0,

    .unk1 = 0,

    .state = DISABLE_INPUT_ALLOW_FUNCPTRS,

    .rows = 0,

    .funcPtr = UDCTRM_OM_FuncPtr,

    .drawStyle = 0,

    .posX_prev = 0,
    .posY_prev = 0,

    .rowSelected = 0,

    .unk1c = 0,
    .unk1e = 0,

    .width = 0,
    .height = 0,

    .ptrNextBox_InHierarchy = 0,
    .ptrPrevBox_InHierarchy = 0,
};

struct MenuRow UDCTRM_OM_MenuRows_ScrapbookUnlocked[] =
{
    MENU_ROW(UDCTRM_OM_ROW_ADVENTURE, 76, UDCTRM_OM_ROW_ADVENTURE, UDCTRM_OM_ROW_TIME_TRIAL, UDCTRM_OM_ROW_ADVENTURE, UDCTRM_OM_ROW_ADVENTURE),
    MENU_ROW(UDCTRM_OM_ROW_TIME_TRIAL, 77, UDCTRM_OM_ROW_ADVENTURE, UDCTRM_OM_ROW_ARCADE, UDCTRM_OM_ROW_TIME_TRIAL, UDCTRM_OM_ROW_TIME_TRIAL),
    MENU_ROW(UDCTRM_OM_ROW_ARCADE, 78, UDCTRM_OM_ROW_TIME_TRIAL, UDCTRM_OM_ROW_VERSUS, UDCTRM_OM_ROW_ARCADE, UDCTRM_OM_ROW_ARCADE),
    MENU_ROW(UDCTRM_OM_ROW_VERSUS, 79, UDCTRM_OM_ROW_ARCADE, UDCTRM_OM_ROW_BATTLE, UDCTRM_OM_ROW_VERSUS, UDCTRM_OM_ROW_VERSUS),
    MENU_ROW(UDCTRM_OM_ROW_BATTLE, 80, UDCTRM_OM_ROW_VERSUS, UDCTRM_OM_ROW_HIGH_SCORE, UDCTRM_OM_ROW_BATTLE, UDCTRM_OM_ROW_BATTLE),
    MENU_ROW(UDCTRM_OM_ROW_HIGH_SCORE, 81, UDCTRM_OM_ROW_BATTLE, UDCTRM_OM_ROW_SCRAPBOOK, UDCTRM_OM_ROW_HIGH_SCORE, UDCTRM_OM_ROW_HIGH_SCORE),
    MENU_ROW(UDCTRM_OM_ROW_SCRAPBOOK, 564, UDCTRM_OM_ROW_HIGH_SCORE, UDCTRM_OM_ROW_OPTIONS, UDCTRM_OM_ROW_SCRAPBOOK, UDCTRM_OM_ROW_SCRAPBOOK),
    MENU_ROW(UDCTRM_OM_ROW_OPTIONS, 14, UDCTRM_OM_ROW_SCRAPBOOK, UDCTRM_OM_ROW_OPTIONS, UDCTRM_OM_ROW_OPTIONS, UDCTRM_OM_ROW_OPTIONS),
    FINALIZER_ROW
};