#include <common.h>

#include "..\..\..\include\helper_menu_box.h"

////////////////// Main Menu Rows //////////////////

#define UDCTRM_MM_ROW_ADVENTURE 0
#define UDCTRM_MM_ROW_TIME_TRIAL 1
#define UDCTRM_MM_ROW_ARCADE 2
#define UDCTRM_MM_ROW_VERSUS 3
#define UDCTRM_MM_ROW_BATTLE 4
#define UDCTRM_MM_ROW_HIGH_SCORE 5
#define UDCTRM_MM_ROW_OPTIONS 6
#define UDCTRM_MM_ROW_SCRAPBOOK 7
#define UDCTRM_MM_NUM_ROWS 8

struct MenuRow UDCTRM_MM_MenuRows[] =
{
    MENU_ROW(UDCTRM_MM_ROW_ADVENTURE, 76, UDCTRM_MM_ROW_ADVENTURE, UDCTRM_MM_ROW_TIME_TRIAL, UDCTRM_MM_ROW_ADVENTURE, UDCTRM_MM_ROW_ADVENTURE),
    MENU_ROW(UDCTRM_MM_ROW_TIME_TRIAL, 77, UDCTRM_MM_ROW_ADVENTURE, UDCTRM_MM_ROW_ARCADE, UDCTRM_MM_ROW_TIME_TRIAL, UDCTRM_MM_ROW_TIME_TRIAL),
    MENU_ROW(UDCTRM_MM_ROW_ARCADE, 78, UDCTRM_MM_ROW_TIME_TRIAL, UDCTRM_MM_ROW_VERSUS, UDCTRM_MM_ROW_ARCADE, UDCTRM_MM_ROW_ARCADE),
    MENU_ROW(UDCTRM_MM_ROW_VERSUS, 79, UDCTRM_MM_ROW_ARCADE, UDCTRM_MM_ROW_BATTLE, UDCTRM_MM_ROW_VERSUS, UDCTRM_MM_ROW_VERSUS),
    MENU_ROW(UDCTRM_MM_ROW_BATTLE, 80, UDCTRM_MM_ROW_VERSUS, UDCTRM_MM_ROW_HIGH_SCORE, UDCTRM_MM_ROW_BATTLE, UDCTRM_MM_ROW_BATTLE),
    MENU_ROW(UDCTRM_MM_ROW_HIGH_SCORE, 81, UDCTRM_MM_ROW_BATTLE, UDCTRM_MM_ROW_OPTIONS, UDCTRM_MM_ROW_HIGH_SCORE, UDCTRM_MM_ROW_HIGH_SCORE),
    MENU_ROW(UDCTRM_MM_ROW_OPTIONS, 14, UDCTRM_MM_ROW_HIGH_SCORE, UDCTRM_MM_ROW_OPTIONS, UDCTRM_MM_ROW_OPTIONS, UDCTRM_MM_ROW_OPTIONS),
    MENU_ROW(UDCTRM_MM_ROW_SCRAPBOOK, -1, UDCTRM_MM_ROW_OPTIONS, UDCTRM_MM_ROW_SCRAPBOOK, UDCTRM_MM_ROW_SCRAPBOOK, UDCTRM_MM_ROW_SCRAPBOOK),
    FINALIZER_ROW
};