#ifndef GAME_VERSION_H
#define GAME_VERSION_H

/* Name of the Game */
#define GAME_NAME "Legacy of Kain: Soul Reaver"

/* Short Name of the Game */
#define SHORT_GAME_NAME "KAIN2"

/* Default window sizes */
#define GAME_WINDOW_WIDTH (512)
#define GAME_WINDOW_HEIGHT (240)

/* Game version */
#define GAME_MAJOR_VERSION (0)
#define GAME_MINOR_VERSION (6)

/* Compile date and time */
#define GAME_COMPILE_DATE (__DATE__)
#define GAME_COMPILE_TIME (__TIME__)

/* Psy-Q version (required) */
#define PSYQ_REQUIRED_MAJOR_VERSION (4)
#define PSYQ_REQUIRED_MINOR_VERSION (7)

#endif