#ifndef UTILS_H_TRACKROM
#define UTILS_H_TRACKROM

#include <common.h>

#define CUSTOM_LEVEL_ID 0
#define DISABLE_GHOSTS

#define TRIGGER_HOT_RELOAD (volatile int*) 0x8000C000
#define TRIGGER_VRM_RELOAD (volatile int*) 0x8000C004
#define GHOST_READY (volatile int*) 0x8000C008
#define CHAR_MODEL_PTRS (struct Model**) 0x8000C010

#define VRM_FILESIZE 0x70038
#define GHOST_FILESIZE 0x3E00

#define FREE_MEM_START 0x80200000
#define VRM_LOCATION FREE_MEM_START
#define GHOST_SIZE_LOCATION (VRM_LOCATION + VRM_FILESIZE)
#define GHOST_LOCATION (GHOST_SIZE_LOCATION + sizeof(int))
#define DRIVER_LOCATION (GHOST_LOCATION + GHOST_FILESIZE)
/* First free byte: 0x802BE670 : Pre-calculated value after every driver is loaded */
#define INPUT_LOCATION 0x802BE670
#define CUSTOM_LEV_MAP_LOCATION 0x80300000
#define CUSTOM_LEV_LOCATION (CUSTOM_LEV_MAP_LOCATION + sizeof(int))

#define MAX_RECORDED_FRAMES ((CUSTOM_LEV_MAP_LOCATION - INPUT_LOCATION) / 2)

#define CUSTOM_VRAM_ADDR (char*) VRM_LOCATION
#define GHOST_SIZE_ADDR (int*) GHOST_SIZE_LOCATION
#define GHOST_ADDR (char*) GHOST_LOCATION
#define DRIVER_ADDR (char*) DRIVER_LOCATION
#define CUSTOM_MAP_PTR_ADDR (int*) CUSTOM_LEV_MAP_LOCATION
#define CUSTOM_LEV_ADDR (char*) CUSTOM_LEV_LOCATION

enum GameState
{
    STATE_INIT = 0,
    STATE_LOADING_END = 1,
    STATE_RESET_STAGE = 2,
    STATE_GAMEPLAY = 3,
};

enum HotReloadSteps
{
    HOT_RELOAD_DONE = 0,
    HOT_RELOAD_START = 1,
    HOT_RELOAD_LOAD = 2,
    HOT_RELOAD_READY = 3,
    HOT_RELOAD_EXEC = 4,
};

void HotReload();
void HotReloadVRAM();

#endif