#define REBUILD_PS1

#include <common.h>

// not in OG game, does not fit byte budget,
// random testing to learn more about the game 
#include "TEST_226.c"
#include "TEST_DrawSkybox.c"
#include "TEST_DrawInstances.c"
#include "TEST_ConvertRotToMatrix.c"
#include "TEST_ThTickRunBucket.c"
#include "TEST_ThTickSetAndExec.c"

// replace regular functions with TEST,
// for as long as there is no DECOMP variant
#define ConvertRotToMatrix TEST_ConvertRotToMatrix
#define ThTick_SetAndExec TEST_ThTickSetAndExec

// replace custom ND version with regular library version
#define SquareRoot0_stub SquareRoot0

// temporarily require manual including
#include "../decompile/General/AltMods/Mods3.c"
#include "../decompile/General/AltMods/Mods4.c"

#include "../decompile/General/MAIN/MAIN_AAA_BigBlock1.c"

#include "../decompile/General/CAMERA/CAM_01_ClearScreen.c"
#include "../decompile/General/CAMERA/CAM_02_Init.c"
#include "../decompile/General/CAMERA/CAM_04_Path_GetNumPoints.c"
#include "../decompile/General/CAMERA/CAM_05_Path_Move.c"
#include "../decompile/General/CAMERA/CAM_06_StartOfRace.c"
#include "../decompile/General/CAMERA/CAM_10_ProcessTransition.c"
#include "../decompile/General/CAMERA/CAM_16_SetDesiredPosRot.c"

#include "../decompile/General/CDSYS/CDSYS_00_Init.c" 
#include "../decompile/General/CDSYS/CDSYS_01_GetFilePosInt.c" 
#include "../decompile/General/CDSYS/CDSYS_02_SetMode_StreamData.c" 
#include "../decompile/General/CDSYS/CDSYS_03_SetMode_StreamAudio.c" 
#include "../decompile/General/CDSYS/CDSYS_04_SetXAToLang.c" 
#include "../decompile/General/CDSYS/CDSYS_05_XaCallbackCdSync.c" 
#include "../decompile/General/CDSYS/CDSYS_06_XaCallbackCdReady.c" 
#include "../decompile/General/CDSYS/CDSYS_07_SpuCallbackIRQ.c" 
#include "../decompile/General/CDSYS/CDSYS_08_SpuCallbackTransfer.c" 
#include "../decompile/General/CDSYS/CDSYS_09_SpuEnableIRQ.c" 
#include "../decompile/General/CDSYS/CDSYS_10_SpuDisableIRQ.c" 
#include "../decompile/General/CDSYS/CDSYS_11_SpuGetMaxSample.c"
#include "../decompile/General/CDSYS/CDSYS_12_XAGetNumTracks.c" 
#include "../decompile/General/CDSYS/CDSYS_13_XASeek.c" 
#include "../decompile/General/CDSYS/CDSYS_14_XAGetTrackLength.c" 
#include "../decompile/General/CDSYS/CDSYS_15_XAPlay.c" 
#include "../decompile/General/CDSYS/CDSYS_16_XAPauseRequest.c" 
#include "../decompile/General/CDSYS/CDSYS_17_XAPauseForce.c" 
#include "../decompile/General/CDSYS/CDSYS_18_XAPauseAtEnd.c"

#include "../decompile/General/COLL/COLL_00_LevModelMeta.c"

#include "../decompile/General/CTR/CTR_00_Box_DrawWirePrims.c"
#include "../decompile/General/CTR/CTR_01_Box_DrawWireBox.c"
#include "../decompile/General/CTR/CTR_02_Box_DrawClearBox.c"
#include "../decompile/General/CTR/CTR_03_Box_DrawSolidBox.c"
#include "../decompile/General/CTR/CTR_04_CycleTex_LEV.c"
#include "../decompile/General/CTR/CTR_05_CycleTex_Model.c"
#include "../decompile/General/CTR/CTR_06_CycleTex_AllModels.c"
#include "../decompile/General/CTR/CTR_11_ErrorScreen.c"
//#include "../decompile/General/CTR/CTR_16_MatrixToRot.c"

#include "../decompile/General/DebugFont/DebugFont_0_Init.c"
#include "../decompile/General/DebugFont/DebugFont_1_DrawNumbers.c"

#include "../decompile/General/DecalFont/DecalFont_0_GetLineWidthStrlen.c"
#include "../decompile/General/DecalFont/DecalFont_1_GetLineWidth.c"
#include "../decompile/General/DecalFont/DecalFont_2_DrawLineStrlen.c"
#include "../decompile/General/DecalFont/DecalFont_3_DrawLine.c"
#include "../decompile/General/DecalFont/DecalFont_4_DrawLineOT.c"
#include "../decompile/General/DecalFont/DecalFont_5_DrawMultiLineStrlen.c"
#include "../decompile/General/DecalFont/DecalFont_6_DrawMultiLine.c"

#include "../decompile/General/DecalGlobal/DecalGlobal_1_Clear.c"
#include "../decompile/General/DecalGlobal/DecalGlobal_2_Store.c"

#include "../decompile/General/DecalHUD/DecalHUD_0_DrawPolyFT4.c"
#include "../decompile/General/DecalHUD/DecalHUD_1_DrawWeapon.c"
#include "../decompile/General/DecalHUD/DecalHUD_2_DrawPolyGT4.c"
#include "../decompile/General/DecalHUD/DecalHUD_3_Arrow2D.c"

#include "../decompile/General/Display/DISPLAY_2_Swap.c"

#include "../decompile/General/DotLights/DotLights_1_AudioAndVideo.c"

#include "../decompile/General/DropRain/DropRain_0_MakeSound.c"
#include "../decompile/General/DropRain/DropRain_1_Reset.c"

#include "../decompile/General/ElimBG/ElimBG_0_SaveScreenshot_Chunk.c"
#include "../decompile/General/ElimBG/ElimBG_1_SaveScreenshot_Full.c"
#include "../decompile/General/ElimBG/ElimBG_2_Activate.c"
#include "../decompile/General/ElimBG/ElimBG_3_ToggleInstance.c"
#include "../decompile/General/ElimBG/ElimBG_4_ToggleAllInstances.c"
#include "../decompile/General/ElimBG/ElimBG_5_HandleState.c"
#include "../decompile/General/ElimBG/ElimBG_6_Deactivate.c"

//#include "../decompile/General/FLARE/FLARE_0_ThTick.c"
//#include "../decompile/General/FLARE/FLARE_1_Init.c"

#include "../decompile/General/GAMEPAD/GAMEPAD_00_Init.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_01_SetMainMode.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_02_ProcessState.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_03_PollVsync.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_04_GetNumConnected.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_05_ProcessHold.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_06_ProcessSticks.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_07_ProcessTapRelease.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_08_ProcessMotors.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_09_ProcessAnyoneVars.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_10_JogCon1.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_11_JogCon2.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_12_ShockFreq.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_13_ShockForce1.c"
#include "../decompile/General/GAMEPAD/GAMEPAD_14_ShockForce2.c"

//#include "../decompile/General/GAMEPROG/GAMEPROG_00_AdvPercent.c"
#include "../decompile/General/GAMEPROG/GAMEPROG_01_ResetHighScores.c"
#include "../decompile/General/GAMEPROG/GAMEPROG_02_CheckGhostsBeaten.c"
#include "../decompile/General/GAMEPROG/GAMEPROG_03_NewProfile_OutsideAdv.c"
//#include "../decompile/General/GAMEPROG/GAMEPROG_04_InitFullMemcard.c"
#include "../decompile/General/GAMEPROG/GAMEPROG_05_NewProfile_InsideAdv.c"
//#include "../decompile/General/GAMEPROG/GAMEPROG_06_SaveCupProgress.c"
//#include "../decompile/General/GAMEPROG/GAMEPROG_07_SyncGameAndCard.c"
#include "../decompile/General/GAMEPROG/GAMEPROG_08_NewGame_OnBoot.c"
#include "../decompile/General/GAMEPROG/GAMEPROG_09_GetPtrHighScoreTrack.c"

#include "../decompile/General/GHOST/GhostReplay_00_ThTick.c"
#include "../decompile/General/GHOST/GhostReplay_01_Init1.c"
#include "../decompile/General/GHOST/GhostReplay_02_Init2.c"

#include "../decompile/General/GHOST/GhostTape_00_Start.c"
#include "../decompile/General/GHOST/GhostTape_01_End.c"
#include "../decompile/General/GHOST/GhostTape_02_WriteMoves.c"
#include "../decompile/General/GHOST/GhostTape_03_WriteBoosts.c"
#include "../decompile/General/GHOST/GhostTape_04_Destroy.c"

#include "../decompile/General/HOWL/h01_CountSounds.c"
#include "../decompile/General/HOWL/h02_OtherFX_Play.c"
#include "../decompile/General/HOWL/h03_OtherFX_Play_Echo.c"
#include "../decompile/General/HOWL/h04_OtherFX_Play_LowLevel.c"
#include "../decompile/General/HOWL/h05_OtherFX_Modify.c"
#include "../decompile/General/HOWL/h06_OtherFX_Stop1.c"
#include "../decompile/General/HOWL/h07_OtherFX_Stop2.c"
#include "../decompile/General/HOWL/h08_EngineAudio_InitOnce.c"
#include "../decompile/General/HOWL/h09_EngineAudio_Recalculate.c"
#include "../decompile/General/HOWL/h10_EngineAudio_Stop.c"
#include "../decompile/General/HOWL/h11_SetReverbMode.c"
#include "../decompile/General/HOWL/h12_CseqMusic_Start.c"
#include "../decompile/General/HOWL/h13_CseqMusic_Pause.c"
#include "../decompile/General/HOWL/h14_CseqMusic_Resume.c"
#include "../decompile/General/HOWL/h15_CseqMusic_ChangeVolume.c"
#include "../decompile/General/HOWL/h16_CseqMusic_Restart.c"
#include "../decompile/General/HOWL/h17_CseqMusic_ChangeTempo.c"
#include "../decompile/General/HOWL/h18_CseqMusic_AdvHubSwap.c"
#include "../decompile/General/HOWL/h19_CseqMusic_Stop.c"
#include "../decompile/General/HOWL/h20_CseqMusic_StopAll.c"
#include "../decompile/General/HOWL/h21_Bank_ResetAllocator.c"
#include "../decompile/General/HOWL/h22_Bank_Alloc.c"
#include "../decompile/General/HOWL/h23_Bank_AssignSpuAddrs.c"
#include "../decompile/General/HOWL/h24_Bank_Destroy.c"
#include "../decompile/General/HOWL/h25_Bank_ClearInRange.c"
#include "../decompile/General/HOWL/h26_Bank_Load.c"
#include "../decompile/General/HOWL/h27_Bank_DestroyLast.c"
#include "../decompile/General/HOWL/h28_Bank_DestroyUntilIndex.c"
#include "../decompile/General/HOWL/h29_Bank_DestroyAll.c"
#include "../decompile/General/HOWL/h30_howl_InstrumentPitch.c"
#include "../decompile/General/HOWL/h31_howl_InitGlobals.c"
#include "../decompile/General/HOWL/h32_howl_ParseHeader.c"
#include "../decompile/General/HOWL/h33_howl_ParseCseqHeader.c"
#include "../decompile/General/HOWL/h34_howl_LoadHeader.c"
#include "../decompile/General/HOWL/h35_howl_SetSong.c"
#include "../decompile/General/HOWL/h36_howl_LoadSong.c"
#include "../decompile/General/HOWL/h37_howl_ErasePtrCseqHeader.c"
#include "../decompile/General/HOWL/h38_howl_GetNextNote.c"
#include "../decompile/General/HOWL/h39_cseq_opcode01_noteoff.c"
#include "../decompile/General/HOWL/h40_cseq_opcode03.c"
#include "../decompile/General/HOWL/h41_howl_InitChannelAttr_Music.c"
#include "../decompile/General/HOWL/h42_cseq_opcode_from06and07.c"
#include "../decompile/General/HOWL/h43_cseq_opcode05_noteon.c"
#include "../decompile/General/HOWL/h44_cseq_opcode06.c"
#include "../decompile/General/HOWL/h45_cseq_opcode07.c"
#include "../decompile/General/HOWL/h46_cseq_opcode08.c"
#include "../decompile/General/HOWL/h47_cseq_opcode09.c"
#include "../decompile/General/HOWL/h48_cseq_opcode0a.c"
#include "../decompile/General/HOWL/h49_SongPool_FindFreeChannel.c"
#include "../decompile/General/HOWL/h50_SongPool_CalculateTempo.c"
#include "../decompile/General/HOWL/h51_SongPool_ChangeTempo.c"
#include "../decompile/General/HOWL/h52_SongPool_Start.c"
#include "../decompile/General/HOWL/h53_SongPool_Volume.c"
#include "../decompile/General/HOWL/h54_SongPool_AdvHub1.c"
#include "../decompile/General/HOWL/h55_SongPool_AdvHub2.c"
#include "../decompile/General/HOWL/h56_SongPool_StopCseq.c"
#include "../decompile/General/HOWL/h57_SongPool_StopAllCseq.c"
#include "../decompile/General/HOWL/h58_howl_Disable.c"
#include "../decompile/General/HOWL/h59_UpdateChannelVol_EngineFX.c"
#include "../decompile/General/HOWL/h60_UpdateChannelVol_OtherFX.c"
#include "../decompile/General/HOWL/h61_UpdateChannelVol_Music.c"
#include "../decompile/General/HOWL/h62_UpdateChannelVol_EngineFX_All.c"
#include "../decompile/General/HOWL/h63_UpdateChannelVol_Music_All.c"
#include "../decompile/General/HOWL/h64_UpdateChannelVol_OtherFX_All.c"
#include "../decompile/General/HOWL/h65_howl_VolumeGet.c"
#include "../decompile/General/HOWL/h66_howl_VolumeSet.c"
#include "../decompile/General/HOWL/h67_howl_ModeGet.c"
#include "../decompile/General/HOWL/h68_howl_ModeSet.c"
#include "../decompile/General/HOWL/h69_OptionsMenu_TestSound.c"
#include "../decompile/General/HOWL/h70_Smart_EnterCriticalSection.c"
#include "../decompile/General/HOWL/h71_Smart_ExitCriticalSection.c"
#include "../decompile/General/HOWL/h72_Channel_SetVolume.c"
#include "../decompile/General/HOWL/h73_Channel_FindSound.c"
#include "../decompile/General/HOWL/h74_Channel_AllocSlot_AntiSpam.c"
#include "../decompile/General/HOWL/h75_Channel_AllocSlot.c"
#include "../decompile/General/HOWL/h76_Channel_SearchFX_EditAttr.c"
#include "../decompile/General/HOWL/h77_Channel_SearchFX_Destroy.c"
#include "../decompile/General/HOWL/h78_Channel_DestroyAll_LowLevel.c"
#include "../decompile/General/HOWL/h79_Channel_ParseSongToChannels.c"
#include "../decompile/General/HOWL/h80_Channel_UpdateChannels.c"
#include "../decompile/General/HOWL/h81_Cutscene_VolumeBackup.c"
#include "../decompile/General/HOWL/h82_Cutscene_VolumeRestore.c"
#include "../decompile/General/HOWL/h83_howl_PlayAudio_Update.c"
#include "../decompile/General/HOWL/h84_howl_InitChannelAttr_EngineFX.c"
#include "../decompile/General/HOWL/h85_howl_InitChannelAttr_OtherFX.c"
#include "../decompile/General/HOWL/h86_howl_PauseAudio.c"
#include "../decompile/General/HOWL/h87_howl_UnPauseChannel.c"
#include "../decompile/General/HOWL/h88_howl_UnPauseAudio.c"
#include "../decompile/General/HOWL/h89_howl_StopAudio.c"
#include "../decompile/General/HOWL/h90_Voiceline_PoolInit.c"
#include "../decompile/General/HOWL/h91_Voiceline_ClearTimeStamp.c"
#include "../decompile/General/HOWL/h92_Voiceline_PoolClear.c"
#include "../decompile/General/HOWL/h93_Voiceline_StopAll.c"
#include "../decompile/General/HOWL/h94_Voiceline_ToggleEnable.c"
// skip h95, h96, h97 (requires CDSYS fix from void to int), h98 (empty)
#include "../decompile/General/HOWL/h99_Voiceline_SetDefaults.c"
#include "../decompile/General/HOWL/h100_Audio_SetState.c"
#include "../decompile/General/HOWL/h101_Audio_SetState_Safe.c"
#include "../decompile/General/HOWL/h102_Audio_AdvHub_SwapSong.c"
#include "../decompile/General/HOWL/h103_Audio_SetMaskSong.c"
#include "../decompile/General/HOWL/h104_Audio_Update1.c"
#include "../decompile/General/HOWL/h105_Audio_SetDefaults.c"
#include "../decompile/General/HOWL/h106_Audio_SetReverbMode.c"
#include "../decompile/General/HOWL/h107_Music_SetIntro.c"
#include "../decompile/General/HOWL/h108_Music_LoadBanks.c"
#include "../decompile/General/HOWL/h109_Music_AsyncParseBanks.c"
#include "../decompile/General/HOWL/h110_Music_SetDefaults.c"
#include "../decompile/General/HOWL/h111_Music_Adjust.c"
#include "../decompile/General/HOWL/h112_Music_LowerVolume.c"
#include "../decompile/General/HOWL/h113_Music_RaiseVolume.c"
#include "../decompile/General/HOWL/h114_Music_Restart.c"
#include "../decompile/General/HOWL/h115_Music_Stop.c"
#include "../decompile/General/HOWL/h116_Music_Start.c"
#include "../decompile/General/HOWL/h117_Music_End.c"
#include "../decompile/General/HOWL/h118_Music_GetHighestSongPlayIndex.c"

#include "../decompile/General/INSTANCE/INSTANCE_00_Birth.c"
#include "../decompile/General/INSTANCE/INSTANCE_01_Birth3D.c"
#include "../decompile/General/INSTANCE/INSTANCE_02_Birth2D.c"
#include "../decompile/General/INSTANCE/INSTANCE_03_BirthWithThread.c"
#include "../decompile/General/INSTANCE/INSTANCE_04_BirthWithThread_Stack.c"
#include "../decompile/General/INSTANCE/INSTANCE_05_Death.c"
#include "../decompile/General/INSTANCE/INSTANCE_06_LevInitAll.c"
//#include "../decompile/General/INSTANCE/INSTANCE_07_LevDelayedLInBs.c"
#include "../decompile/General/INSTANCE/INSTANCE_08_GetNumAnimFrames.c"

#include "../decompile/General/JitPool/JitPool_0_Clear.c"
#include "../decompile/General/JitPool/JitPool_1_Init.c"
#include "../decompile/General/JitPool/JitPool_2_Add.c"
#include "../decompile/General/JitPool/JitPool_3_Remove.c"

#include "../decompile/General/LevInstDef/LevInstDef_0_UnPack.c"
#include "../decompile/General/LevInstDef/LevInstDef_1_RePack.c"

#include "../decompile/General/LibraryOfModels/LibraryOfModels_0_Store.c"
#include "../decompile/General/LibraryOfModels/LibraryOfModels_1_Clear.c"

#include "../decompile/General/LinkedCollide/LinkedCollide_2_Hitbox.c"

#include "../decompile/General/LIST/LIST_0_Clear.c"
#include "../decompile/General/LIST/LIST_1_AddFront.c"
#include "../decompile/General/LIST/LIST_2_AddBack.c"
#include "../decompile/General/LIST/LIST_3_GetNextItem.c"
#include "../decompile/General/LIST/LIST_4_GetFirstItem.c"
#include "../decompile/General/LIST/LIST_5_RemoveMember.c"
#include "../decompile/General/LIST/LIST_6_RemoveFront.c"
#include "../decompile/General/LIST/LIST_7_RemoveBack.c"
#include "../decompile/General/LIST/LIST_8_Init.c"

#include "../decompile/General/LOAD/LOAD_00_Callback_Overlay_Generic.c"
#include "../decompile/General/LOAD/LOAD_01_Callback_Overlay_230.c"
#include "../decompile/General/LOAD/LOAD_02_Callback_Overlay_231.c"
#include "../decompile/General/LOAD/LOAD_03_Callback_Overlay_232.c"
#include "../decompile/General/LOAD/LOAD_04_Callback_Overlay_233.c"
#include "../decompile/General/LOAD/LOAD_05_Callback_MaskHints3D.c"
#include "../decompile/General/LOAD/LOAD_06_Callback_Podiums.c"
#include "../decompile/General/LOAD/LOAD_07_Callback_LEV.c"
#include "../decompile/General/LOAD/LOAD_08_Callback_LEV_Adv.c"
#include "../decompile/General/LOAD/LOAD_09_Callback_DriverModels.c"
// hole
#include "../decompile/General/LOAD/LOAD_11_GlobalModelPtrs_MPK.c"
// hole
#include "../decompile/General/LOAD/LOAD_13_StringToUpper.c" 
#include "../decompile/General/LOAD/LOAD_14_InitCD.c" 
#include "../decompile/General/LOAD/LOAD_15_ReadDirectory.c" 
#include "../decompile/General/LOAD/LOAD_16_DramFileCallback.c"
#include "../decompile/General/LOAD/LOAD_17_DramFile.c"
#include "../decompile/General/LOAD/LOAD_18_VramFileCallback.c"
#include "../decompile/General/LOAD/LOAD_19_VramFile.c" 
#include "../decompile/General/LOAD/LOAD_20_ReadFileASyncCallback.c"
#include "../decompile/General/LOAD/LOAD_21_ReadFile.c"
#include "../decompile/General/LOAD/LOAD_22_ReadFile_NoCallback.c"
#include "../decompile/General/LOAD/LOAD_23_FindFile.c"
#include "../decompile/General/LOAD/LOAD_24_HowlHeaderSectors.c"
#include "../decompile/General/LOAD/LOAD_25_HowlCallback.c"
#include "../decompile/General/LOAD/LOAD_26_HowlSectorChainStart.c"
#include "../decompile/General/LOAD/LOAD_27_HowlSectorChainEnd.c"
#include "../decompile/General/LOAD/LOAD_28_RunPtrMap.c"
#include "../decompile/General/LOAD/LOAD_29_Robots2P.c"
#include "../decompile/General/LOAD/LOAD_30_Robots1P.c"
#include "../decompile/General/LOAD/LOAD_31_DriverMPK.c"
#include "../decompile/General/LOAD/LOAD_32_LangFile.c"
#include "../decompile/General/LOAD/LOAD_33_GetBigfileIndex.c"
#include "../decompile/General/LOAD/LOAD_34_AppendQueue.c"
#include "../decompile/General/LOAD/LOAD_35_CDRequestCallback.c"
#include "../decompile/General/LOAD/LOAD_36_NextQueuedFile.c"
// hole
#include "../decompile/General/LOAD/LOAD_40_OvrLOD.c"
#include "../decompile/General/LOAD/LOAD_41_OvrEndRace.c"
#include "../decompile/General/LOAD/LOAD_42_OvrThreads.c"
#include "../decompile/General/LOAD/LOAD_43_GetAdvPackIndex.c"
#include "../decompile/General/LOAD/LOAD_44_TenStages.c"
#include "../decompile/General/LOAD/LOAD_45_TalkingMask.c"
#include "../decompile/General/LOAD/LOAD_46_LevelFile.c"
#include "../decompile/General/LOAD/LOAD_47_IsOpen_RacingOrBattle.c"
#include "../decompile/General/LOAD/LOAD_48_IsOpen_MainMenu.c"
#include "../decompile/General/LOAD/LOAD_49_IsOpen_AdvHub.c"
#include "../decompile/General/LOAD/LOAD_50_IsOpen_Podiums.c"

#include "../decompile/General/MAIN/MainDB_00_GetClipSize.c"
#include "../decompile/General/MAIN/MainDB_01_PrimMem.c"
#include "../decompile/General/MAIN/MainDB_02_OTMem.c"
#include "../decompile/General/MAIN/MainDrawCb_00_DrawSync.c"
#include "../decompile/General/MAIN/MainDrawCb_01_Vsync.c"

#include "../decompile/General/MAIN/MainFrame_00_TogglePauseAudio.c"
#include "../decompile/General/MAIN/MainFrame_01_ResetDB.c"
#include "../decompile/General/MAIN/MainFrame_02_GameLogic.c"
#include "../decompile/General/MAIN/MainFrame_07_RequestMaskHint.c"
#include "../decompile/General/MAIN/MainFrame_08_RenderFrame.c"

#include "../decompile/General/MAIN/MainFreeze_04_MenuPtrQuit.c"
#include "../decompile/General/MAIN/MainFreeze_05_SafeAdvDestroy.c"
#include "../decompile/General/MAIN/MainFreeze_06_MenuPtrDefault.c"
#include "../decompile/General/MAIN/MainFreeze_07_GetMenuPtr.c"
#include "../decompile/General/MAIN/MainFreeze_08_IfPressStart.c"

#include "../decompile/General/MAIN/MainGameStart_00_Initialize.c"

#include "../decompile/General/MAIN/MainRaceTrack_00_StartLoad.c"
#include "../decompile/General/MAIN/MainRaceTrack_01_RequestLoad.c"

#include "../decompile/General/MATH/MATH_0_Sin.c"
#include "../decompile/General/MATH/MATH_1_Cos.c"

#include "../decompile/General/MEMCARD/MEMCARD_06_InitCard.c"

#include "../decompile/General/MEMPACK/MEMPACK_00_Init.c" 
#include "../decompile/General/MEMPACK/MEMPACK_01_SwapPacks.c" 
#include "../decompile/General/MEMPACK/MEMPACK_02_NewPack_StartEnd.c" 
#include "../decompile/General/MEMPACK/MEMPACK_03_GetFreeBytes.c" 
#include "../decompile/General/MEMPACK/MEMPACK_04_AllocMem.c" 
#include "../decompile/General/MEMPACK/MEMPACK_05_AllocHighMem.c" 
#include "../decompile/General/MEMPACK/MEMPACK_06_ClearHighMem.c" 
#include "../decompile/General/MEMPACK/MEMPACK_07_ReallocMem.c" 
#include "../decompile/General/MEMPACK/MEMPACK_08_PushState.c" 
#include "../decompile/General/MEMPACK/MEMPACK_09_ClearLowMem.c" 
#include "../decompile/General/MEMPACK/MEMPACK_10_PopState.c" 
#include "../decompile/General/MEMPACK/MEMPACK_11_PopToState.c"

#include "../decompile/General/MixRNG/MixRNG_0_Scramble.c"

#include "../decompile/General/PROC/PROC_00_DestroyTracker.c"
#include "../decompile/General/PROC/PROC_01_DestroyInstance.c"
#include "../decompile/General/PROC/PROC_02_DestroyObject.c"
#include "../decompile/General/PROC/PROC_03_DestroySelf.c"
#include "../decompile/General/PROC/PROC_04_DestroyBloodline.c"
#include "../decompile/General/PROC/PROC_05_CheckBloodlineForDead.c"
#include "../decompile/General/PROC/PROC_06_CheckAllForDead.c"
#include "../decompile/General/PROC/PROC_07_BirthWithObject.c"
#include "../decompile/General/PROC/PROC_08_CollidePointWithSelf.c"
#include "../decompile/General/PROC/PROC_09_CollidePointWithBucket.c"
#include "../decompile/General/PROC/PROC_10_SearchForModel.c"

#include "../decompile/General/PushBuffer/PushBuffer_00_Init.c"
#include "../decompile/General/PushBuffer/PushBuffer_01_SetPsyqGeom.c"

#include "../decompile/General/PushBuffer/PushBuffer_03_SetDrawEnv_Normal.c"
#include "../decompile/General/PushBuffer/PushBuffer_04_SetMatrixVP.c"

#include "../decompile/General/PushBuffer/PushBuffer_07_FadeOneWindow.c"
#include "../decompile/General/PushBuffer/PushBuffer_08_FadeAllWindows.c"

#include "../decompile/General/QueueLoadTrack/QueueLoadTrack_0_MenuProc.c"
#include "../decompile/General/QueueLoadTrack/QueueLoadTrack_1_GetMenuPtr.c"

#include "../decompile/General/RaceFlag/RaceFlag_00_MoveModels.c"
#include "../decompile/General/RaceFlag/RaceFlag_01_IsFullyOnScreen.c"
#include "../decompile/General/RaceFlag/RaceFlag_02_IsFullyOffScreen.c"
#include "../decompile/General/RaceFlag/RaceFlag_03_IsTransitioning.c"
#include "../decompile/General/RaceFlag/RaceFlag_04_SetDrawOrder.c"
#include "../decompile/General/RaceFlag/RaceFlag_05_BeginTransition.c"
#include "../decompile/General/RaceFlag/RaceFlag_06_SetFullyOnScreen.c"
#include "../decompile/General/RaceFlag/RaceFlag_07_SetFullyOffScreen.c"
#include "../decompile/General/RaceFlag/RaceFlag_08_SetCanDraw.c"
#include "../decompile/General/RaceFlag/RaceFlag_09_GetCanDraw.c"
#include "../decompile/General/RaceFlag/RaceFlag_10_GetOT.c"
#include "../decompile/General/RaceFlag/RaceFlag_11_ResetTextAnim.c"
#include "../decompile/General/RaceFlag/RaceFlag_12_DrawLoadingString.c"
#include "../decompile/General/RaceFlag/RaceFlag_13_DrawSelf.c"

#include "../decompile/General/RECTMENU/RECTMENU_00_DrawPolyGT4.c"
#include "../decompile/General/RECTMENU/RECTMENU_01_DrawOuterRect_Edge.c"
#include "../decompile/General/RECTMENU/RECTMENU_02_DrawTime.c"
#include "../decompile/General/RECTMENU/RECTMENU_03_DrawRwdBlueRect_Subset.c"
#include "../decompile/General/RECTMENU/RECTMENU_04_DrawRwdBlueRect.c"
#include "../decompile/General/RECTMENU/RECTMENU_05_DrawRwdTriangle.c"
#include "../decompile/General/RECTMENU/RECTMENU_06_DrawOuterRect_LowLevel.c"
#include "../decompile/General/RECTMENU/RECTMENU_07_DrawOuterRect_HighLevel.c"
#include "../decompile/General/RECTMENU/RECTMENU_08_DrawQuip.c"
#include "../decompile/General/RECTMENU/RECTMENU_09_DrawInnerRect.c"
#include "../decompile/General/RECTMENU/RECTMENU_10_DrawFullRect.c"
#include "../decompile/General/RECTMENU/RECTMENU_11_GetHeight.c"
#include "../decompile/General/RECTMENU/RECTMENU_12_GetWidth.c"
#include "../decompile/General/RECTMENU/RECTMENU_13_DrawSelf.c"
#include "../decompile/General/RECTMENU/RECTMENU_14_ClearInput.c"
#include "../decompile/General/RECTMENU/RECTMENU_15_CollectInput.c"
#include "../decompile/General/RECTMENU/RECTMENU_16_ProcessInput.c"
#include "../decompile/General/RECTMENU/RECTMENU_17_ProcessState.c"
#include "../decompile/General/RECTMENU/RECTMENU_18_Show.c"
#include "../decompile/General/RECTMENU/RECTMENU_19_Hide.c"
#include "../decompile/General/RECTMENU/RECTMENU_20_BoolHidden.c"

#include "../decompile/General/SubmitName/SubmitName_0_RestoreName.c"
#include "../decompile/General/SubmitName/SubmitName_1_DrawMenu.c"
#include "../decompile/General/SubmitName/SubmitName_2_MenuProc.c"

#include "../decompile/General/Timer/Timer_0_Init.c"
#include "../decompile/General/Timer/Timer_1_Destroy.c"
#include "../decompile/General/Timer/Timer_2_GetTime_Total.c"
#include "../decompile/General/Timer/Timer_3_GetTime_Elapsed.c"


// UI
#include "../decompile/General/prim.c"
#include "../decompile/General/math.c"
#include "../decompile/General/gte.c"
//#include "../decompile/General/UI/UI_AAA_BigBlock1.c"
#include "../decompile/General/UI/UI_00_SaveLapTime.c"
#include "../decompile/General/UI/UI_01_ThTick_CountPickup.c"
#include "../decompile/General/UI/UI_02_ThTick_Reward.c"
#include "../decompile/General/UI/UI_03_ThTick_CtrLetters.c"
#include "../decompile/General/UI/UI_04_ThTick_big1.c"
#include "../decompile/General/UI/UI_05_ConvertX_2.c"
#include "../decompile/General/UI/UI_06_ConvertY_2.c"
#include "../decompile/General/UI/UI_07_INSTANCE_BirthWithThread.c"
#include "../decompile/General/UI/UI_08_INSTANCE_InitAll.c"
#include "../decompile/General/UI/UI_09_Map_DrawMap.c"
#include "../decompile/General/UI/UI_10_Map_GetIconPos.c"
#include "../decompile/General/UI/UI_11_Map_DrawAdvPlayer.c"
#include "../decompile/General/UI/UI_12_Map_DrawRawIcon.c"
#include "../decompile/General/UI/UI_13_Map_DrawDrivers.c"
#include "../decompile/General/UI/UI_14_Map_DrawGhosts.c"
#include "../decompile/General/UI/UI_15_Map_DrawTracking.c"
#include "../decompile/General/UI/UI_16_WeaponBG_AnimateShine.c"
#include "../decompile/General/UI/UI_17_WeaponBG_DrawShine.c"
#include "../decompile/General/UI/UI_18_TrackerBG.c"
#include "../decompile/General/UI/UI_19_DrawDriverIcon.c"
#include "../decompile/General/UI/UI_20_Lerp2D_Angular.c"
#include "../decompile/General/UI/UI_21_Lerp2D_HUD.c"
#include "../decompile/General/UI/UI_22_Lerp2D_Linear.c"
#include "../decompile/General/UI/UI_23_DrawRaceClock.c"
#include "../decompile/General/UI/UI_24_DrawLimitClock.c"
#include "../decompile/General/UI/UI_25_BattleDrawHeadArrows.c"
#include "../decompile/General/UI/UI_26_TrackerSelf.c"
#include "../decompile/General/UI/UI_27_DrawPosSuffix.c"
#include "../decompile/General/UI/UI_28_DrawLapCount.c"
#include "../decompile/General/UI/UI_29_DrawBattleScores.c"
#include "../decompile/General/UI/UI_30_Weapon_DrawSelf.c"
#include "../decompile/General/UI/UI_31_Weapon_DrawBG.c"
#include "../decompile/General/UI/UI_32_DrawNumWumpa.c"
#include "../decompile/General/UI/UI_33_DrawNumTimebox.c"
#include "../decompile/General/UI/UI_34_DrawNumRelic.c"
#include "../decompile/General/UI/UI_35_DrawNumKey.c"
#include "../decompile/General/UI/UI_36_DrawNumTrophy.c"
#include "../decompile/General/UI/UI_37_DrawNumCrystal.c"
#include "../decompile/General/UI/UI_38_DrawSpeedNeedle.c"
#include "../decompile/General/UI/UI_39_DrawSpeedBG.c"
#include "../decompile/General/UI/UI_40_JumpMeter_Update.c"
#include "../decompile/General/UI/UI_41_JumpMeter_Draw.c"
#include "../decompile/General/UI/UI_42_DrawSlideMeter.c"
#include "../decompile/General/UI/UI_43_DrawRankedDrivers.c"
#include "../decompile/General/UI/UI_44_RenderFrame_Racing.c"
#include "../decompile/General/UI/UI_45_RenderFrame_AdvHub.c"
#include "../decompile/General/UI/UI_46_RenderFrame_CrystChall.c"
#include "../decompile/General/UI/UI_53_RaceEnd_GetDriverClock.c"
//#include "../decompile/General/UI/UI_54_RaceStart_IntroText1P.c"
//#include "../decompile/General/UI/UI_55_RaceEnd_MenuProc.c"
//#include "../decompile/General/UI/UI_56_CupStandings_FinalizeCupRanks.c"
//#include "../decompile/General/UI/UI_57_CupStandings_UpdateCupRanks.c"
//#include "../decompile/General/UI/UI_58_CupStandings_InputAndDraw.c"

#include "../decompile/General/Vehicle/VehBirth_0_TeleportSelf.c"
#include "../decompile/General/Vehicle/VehBirth_1_TeleportAll.c"
// VehBirth_GetModelByName deprecated by better option
#include "../decompile/General/Vehicle/VehBirth_3_SetConsts.c"
#include "../decompile/General/Vehicle/VehBirth_4_EngineAudio_AllPlayers.c"
#include "../decompile/General/Vehicle/VehBirth_5_NullThread.c"
#include "../decompile/General/Vehicle/VehBirth_6_TireSprites.c"
#include "../decompile/General/Vehicle/VehBirth_7_NonGhost.c"
#include "../decompile/General/Vehicle/VehBirth_8_Player.c"

#include "../decompile/General/Vehicle/VehCalc_0_InterpBySpeed.c"
#include "../decompile/General/Vehicle/VehCalc_1_MapToRange.c"
#include "../decompile/General/Vehicle/VehCalc_2_SteerAccel.c"

#include "../decompile/General/Vehicle/VehFire_0_Audio.c"
#include "../decompile/General/Vehicle/VehFire_1_Increment.c"

#include "../decompile/General/Vehicle/VehFrameInst_1_GetNumAnimFrames.c"

#include "../decompile/General/Vehicle/VehPhysForce_0_ConvertSpeedToVec.c"
//#include "../decompile/General/Vehicle/VehPhysForce_AccelTerrainSlope.c"
#include "../decompile/General/Vehicle/VehPhysForce_2_OnApplyForces.c"

#include "../decompile/General/Vehicle/VehPhysGeneral_0_PhysAngular.c"
#include "../decompile/General/Vehicle/VehPhysGeneral_1_LerpQuarterStrength.c"
#include "../decompile/General/Vehicle/VehPhysGeneral_2_LerpToForwards.c"
#include "../decompile/General/Vehicle/VehPhysGeneral_5_SetHeldItem.c"
#include "../decompile/General/Vehicle/VehPhysGeneral_6_GetBaseSpeed.c"

#include "../decompile/General/Vehicle/VehPhysJoystick_0_ReturnToRest.c"
#include "../decompile/General/Vehicle/VehPhysJoystick_1_GetStrength.c"
#include "../decompile/General/Vehicle/VehPhysJoystick_2_GetStrengthAbsolute.c"

#include "../decompile/General/Vehicle/VehPhysProc_00_Driving_PhysLinear.c"
#include "../decompile/General/Vehicle/VehPhysProc_01_Driving_Audio.c"
#include "../decompile/General/Vehicle/VehPhysProc_02_Driving_Update.c"
#include "../decompile/General/Vehicle/VehPhysProc_03_Driving_Init.c"

#include "../decompile/General/Vehicle/VehPhysProc_04_FreezeEndEvent_PhysLinear.c"
#include "../decompile/General/Vehicle/VehPhysProc_05_FreezeEndEvent_Init.c"

// everything between VehPhysProc_FreezeEndEvent_Init and VehPickState_NewState
#include "../decompile/General/Vehicle/VehPhysProc_AAA_BigBlock1.c"

#include "../decompile/General/Vehicle/VehPickupItem_0_MaskBoolGoodGuy.c"
#include "../decompile/General/Vehicle/VehPickupItem_4_ShootNow.c"
#include "../decompile/General/Vehicle/VehPickupItem_5_ShootOnCirclePress.c"

#include "../decompile/General/Vehicle/VehStuckProc_11_RevEngine_Update.c"
#include "../decompile/General/Vehicle/VehStuckProc_12_RevEngine_PhysLinear.c"
#include "../decompile/General/Vehicle/VehStuckProc_13_RevEngine_Animate.c"
#include "../decompile/General/Vehicle/VehStuckProc_14_RevEngine_Init.c"
#include "../decompile/General/Vehicle/VehStuckProc_15_Tumble_Update.c"
#include "../decompile/General/Vehicle/VehStuckProc_16_Tumble_PhysLinear.c"
#include "../decompile/General/Vehicle/VehStuckProc_17_Tumble_PhysAngular.c"
#include "../decompile/General/Vehicle/VehStuckProc_18_Tumble_Animate.c"
#include "../decompile/General/Vehicle/VehStuckProc_19_Tumble_Init.c"

#include "../decompile/General/Vehicle/VehTalkMask_0_ThTick.c"
#include "../decompile/General/Vehicle/VehTalkMask_1_Init.c"
#include "../decompile/General/Vehicle/VehTalkMask_2_PlayXA.c"
#include "../decompile/General/Vehicle/VehTalkMask_3_boolNoXA.c"
#include "../decompile/General/Vehicle/VehTalkMask_4_End.c"


// 230
// only put these in the EXE for REBUILD_PC,
// REBUILD_PS1 puts them on BuildList.txt,
// cause R230 and D230 in the symbol table
// go to the overlay
#ifdef REBUILD_PC
#include "../decompile/General/230/R230.c"
#include "../decompile/General/230/D230.c"
#endif

// 230
#include "../decompile/General/230/230_00_38_MM_Battle_DrawIcon_Character.c"
#include "../decompile/General/230/230_39_MM_AdvNewLoad_GetMenuPtr.c"
#include "../decompile/General/230/230_40_54_MM_Characters_AnimateColors.c"
#include "../decompile/General/230/230_55_MM_TrackSelect_Init.c"
#include "../decompile/General/230/230_56_MM_TrackSelect_MenuProc.c"
#include "../decompile/General/230/230_57_MM_TrackSelect_GetMenuPtr.c"
#include "../decompile/General/230/230_58_76_MM_CupSelect_Init.c"

#ifdef REBUILD_PC
//#include "../decompile/General/231/R231.c" //doesn't exist yet
#include "../decompile/General/231/D231.c"
#endif

// 231
#include "../decompile/General/231/231_002_RB_Player_ModifyWumpa.c"
#include "../decompile/General/231/231_003_RB_MinePool_Init.c"
#include "../decompile/General/231/231_004_RB_MinePool_Remove.c"
#include "../decompile/General/231/231_005_RB_MinePool_Add.c"
#include "../decompile/General/231/231_006_RB_Hazard_HurtDriver.c"
#include "../decompile/General/231/231_007_RB_Hazard_CollideWithDrivers.c"
#include "../decompile/General/231/231_008_RB_Hazard_CollideWithBucket.c"
#include "../decompile/General/231/231_009_RB_Hazard_ThCollide_Generic_Alt.c"
#include "../decompile/General/231/231_010_RB_Hazard_ThCollide_Missile.c"
#include "../decompile/General/231/231_011_RB_Hazard_ThCollide_Generic.c"

#include "../decompile/General/231/231_023_RB_Hazard_InterpolateValue.c"
#include "../decompile/General/231/231_024_RB_MovingExplosive_ThTick.c"
#include "../decompile/General/231/231_025_RB_MovingExplosive_Explode.c"

// Can not defrag 055 into GROUP_55_72 until globals are rewritten
#include "../decompile/General/231/231_055_RB_GetThread_ClosestTracker.c"
#include "../decompile/General/231/231_056_072_RB_Baron_ThTick.c"

#include "../decompile/General/231/231_082_085_RB_Armadillo.c"
#include "../decompile/General/231/231_086_088_RB_Fireball.c"
#include "../decompile/General/231/231_099_100_RB_Minecart.c"
#include "../decompile/General/231/231_104_109_RB_Plant.c"
#include "../decompile/General/231/231_110_113_RB_Seal.c"
#include "../decompile/General/231/231_114_115_RB_Snowball.c"
#include "../decompile/General/231/231_116_119_RB_Spider.c"
#include "../decompile/General/231/231_127_129_RB_Turtle.c"

// 232
#ifdef REBUILD_PC
// see notes from 230
#include "../decompile/General/232/R232.c"
#include "../decompile/General/232/D232.c"
#endif

#include "../decompile/General/232/232_Full.c"

#include "../decompile/General/233/233_37_40_CS_Garage.c"
#include "../decompile/General/233/233_zGlobal_gGarage.c"