name: Build main

on:
  push:
    branches:
      - '**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Create result directory
        run: mkdir ${{ runner.temp }}/result
      - name: Build Decomp Debug Linux32 GCC
        run: nix build -L --no-link --keep-going '.?submodules=1#decomp.debug.native32.gcc'
      - name: Build Decomp Debug Linux32 Clang
        run: nix build -L --no-link --keep-going '.?submodules=1#decomp.debug.native32.clang'
      - name: Build Decomp Debug Mingw32 GCC
        run: nix build -L --no-link --keep-going '.?submodules=1#decomp.debug.mingw32.gcc'
      - name: Build Decomp Debug Mingw32 Clang
        run: nix build -L --no-link --keep-going '.?submodules=1#decomp.debug.mingw32.clang'
      - name: Build Retail Release Linux32 GCC
        run: nix build -L --no-link --keep-going '.?submodules=1#retail.release.native32.gcc'
      - name: Build Server Release Linux32 GCC
        run: nix build -L --no-link --keep-going '.?submodules=1#online-server.release.native32.gcc'
      - name: Build Server Release ARM32 GCC
        run: nix build -L --no-link --keep-going '.?submodules=1#online-server.release.arm32.gcc'
      - name: Build Server Release Mingw2 GCC
        run: nix build -L --keep-going '.?submodules=1#online-server.release.mingw32.gcc' -o ${{ runner.temp }}/result/online-server.release.mingw32.gcc
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: online-server-windows
          path: |
            ${{ runner.temp }}/result/online-server.release.mingw32.gcc/bin
